
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/team03-s23-5pm-4
owner: ucsb-cs156-s23
repo_name: team03-s23-5pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjEyNTM2MTg3","is_bot":false,"login":"ameymwalimbe","name":""},"headRefName":"amey-attractionEdit2","number":40,"title":"Amey attraction edit2","url":"https://github.com/ucsb-cs156-s23/team03-s23-5pm-4/pull/40"},{"author":{"id":"MDQ6VXNlcjI5NTg0ODU2","is_bot":false,"login":"strongani","name":"Anikait Mundhra"},"headRefName":"Anikait-restaurantConnection","number":39,"title":"AM/IW Restaurant Frontend/Backend","url":"https://github.com/ucsb-cs156-s23/team03-s23-5pm-4/pull/39"},{"author":{"id":"MDQ6VXNlcjQ0NTMwNzM5","is_bot":false,"login":"SophiaWeiler","name":"Sophia Weiler"},"headRefName":"sophia-attractionTableConnect","number":37,"title":"SW - attractionIndexPage + attractionTable + attractionEditPage","url":"https://github.com/ucsb-cs156-s23/team03-s23-5pm-4/pull/37"}]
