
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/team03-s23-5pm-4
owner: ucsb-cs156-s23
repo_name: team03-s23-5pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjQ0NTMwNzM5","is_bot":false,"login":"SophiaWeiler","name":"Sophia Weiler"},"headRefName":"sophia-attractionsCreateConnect","number":33,"title":"SW - changes to AttractionCreatePage ","url":"https://github.com/ucsb-cs156-s23/team03-s23-5pm-4/pull/33"},{"author":{"id":"MDQ6VXNlcjc5MDY5OTY0","is_bot":false,"login":"zachmiller-ucsb","name":"Zach Miller"},"headRefName":"Zach-integrateBackendTransportIndexPageAndTable","number":32,"title":"Zach integrate backend transport index page and table","url":"https://github.com/ucsb-cs156-s23/team03-s23-5pm-4/pull/32"}]
